"""Add futures_contracts table

Revision ID: 24452ee3c0ae
Revises: 14452ee3c0ae
Create Date: 2025-03-04 13:55:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24452ee3c0ae'
down_revision: Union[str, None] = '14452ee3c0ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('futures_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=False),
    sa.Column('tick_size', sa.Float(), nullable=False),
    sa.Column('contract_size', sa.Float(), nullable=False),
    sa.Column('margin_requirement', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('futures_contracts')
    # ### end Alembic commands ###
